name: 'jacoco-summary'
author: 'Joaquim Rocha'
description: 'Add coverage from JaCoCo report to workflow job summary'
branding: 
  icon: 'shield'
  color: 'green'
inputs:
  jacoco-csv-file:
    description: 'Location of the JaCoCo CSV file'
    required: false
    default: 'build/reports/jacoco/test/jacocoTestReport.csv'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jacoco-csv-file }}
