on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: 'jjmrocha/jacoco-summary@main'
        with:
          jacoco-csv-file: 'testdata/jacocoTestReport.csv'